language: node_js
node_js:
- '6'
notifications:
  slack:
    secure: 0KNCOg7X8I218/9vDojCF9eNU6j5eqNii28FNCxcmOPQ5j6430HT0v583Kr/gCPmWiohjDzyrT6QLNdQt7GOSbBq5YXCWERHuB5G1LrOZw4yksfQ5S3z+S5/g1+hwi6ZbAMvv5IkjTLgrH5MqGTNsXpBtiVqiGbLIY5BxmRQKxwjdhlyc7Xe+32xlxXwnLOmFChYZ/Tw4XQWkK6NyfgJ/9H/xvPdGrJCfPIrVf0svKhBnU7MN9pOikM7McVKAt41VfT9tFdTWTHaK57EhguCOI4amNUsyQqbYYRJKfVygtr1PleBjaA5+w8CMf2EfjCR2kNWGkG6xCXRO5eZWjjNgK1hKhMwX4KxwfZWJWkz7z5dOC8u5XH0JDgWIpp8uTmRBTJLWps6jDBzooON0lfgGCBd/5MM3cjmOXK0TlNpLZZTZSyE2b560ViT7PyRLk9/iMQ/zRB1Lzxpq0bd4YddV0pK4MYubYn/1ZsE9r/79z7yUm4dBbtlV3BYP401wr0xRmg3ftVI5TPpptUgMcpPYMC1AlFWxhCNWsnsnB4jGNV1GLtnjUO72MfpG/U7bccwpnpjrJFeidw/lszPxOVZLJ5ZClJG8uFgiqYo1kjKngSwFO1Y+LK+nY6xxTeDeM3CwAFXHfU0HDeZNEhg2jOb1qIRtGTqEWj6pjeE9F/aGpM=
   email:
    on_success: never
    on_failure: change